class Autogenerated {
  Data? data;
  String? status;
  int? count;
  int? httpStatus;

  Autogenerated({data, status, count, httpStatus});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? Data.fromJson(json['data']) : null;
    status = json['status'];
    count = json['count'];
    httpStatus = json['http_status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
      if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['status'] = status;
    data['count'] = count;
    data['http_status'] = httpStatus;
    return data;
  }
}

class Data {
  List<Banners>? banners;
  List<Promo>? promo;
  List<CollectionItems>? collectionItems;

  Data({banners, promo, collectionItems});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['banners'] != null) {
      banners = <Banners>[];
      json['banners'].forEach((v) {
        banners!.add(Banners.fromJson(v));
      });
    }
    if (json['promo'] != null) {
      promo = <Promo>[];
      json['promo'].forEach((v) {
        promo!.add(Promo.fromJson(v));
      });
    }
    if (json['collection_items'] != null) {
      collectionItems = <CollectionItems>[];
      json['collection_items'].forEach((v) {
        collectionItems!.add(CollectionItems.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (banners != null) {
      data['banners'] = banners!.map((v) => v.toJson()).toList();
    }
    if (promo != null) {
      data['promo'] = promo!.map((v) => v.toJson()).toList();
    }
    if (collectionItems != null) {
      data['collection_items'] =
          collectionItems!.map((v) => v.toJson()).toList();
    }
    return data;
  }

  map(Function(dynamic v) param0) {}
}

class Banners {
  String? id;
  String? image;
  String? title;
  bool? isMobile;
  bool? isDesktop;
  String? href;
  Link? link;

  Banners(
      {id,
      image,
      title,
      isMobile,
      isDesktop,
      href,
      link});

  Banners.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    image = json['image'];
    title = json['title'];
    isMobile = json['is_mobile'];
    isDesktop = json['is_desktop'];
    href = json['href'];
    link = json['link'] != null ? Link.fromJson(json['link']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['image'] = image;
    data['title'] = title;
    data['is_mobile'] = isMobile;
    data['is_desktop'] = isDesktop;
    data['href'] = href;
    if (link != null) {
      data['link'] = link!.toJson();
    }
    return data;
  }
}

class Link {
  String? aggregationId;
  String? external;

  Link({aggregationId, external});

  Link.fromJson(Map<String, dynamic> json) {
    aggregationId = json['aggregation_id'];
    external = json['external'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['aggregation_id'] = aggregationId;
    data['external'] = external;
    return data;
  }
}

class Promo {
  String? id;
  String? createdAt;
  String? itemType;
  List<String>? subcategoryIds;
  String? mainSubcategory;
  String? storeId;
  bool? visible;
  String? description;
  List<String>? images;
  String? name;
  List<CustomInfos>? customInfos;
  List<Prices>? prices;
  int? emergencyStock;
  bool? availableStock;
  double? minPriceValid;
  List<String>? variationItems;
  List<String>? relatedItems;
  String? slug;
  String? brand;
  String? unitType;
  int? incrementValue;
  Shipping? shipping;
  String? keywords;

  Promo(
      {id,
      createdAt,
      itemType,
      subcategoryIds,
      mainSubcategory,
      storeId,
      visible,
      description,
      images,
      name,
      customInfos,
      prices,
      emergencyStock,
      availableStock,
      minPriceValid,
      variationItems,
      relatedItems,
      slug,
      brand,
      unitType,
      incrementValue,
      shipping,
      keywords});

  Promo.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    createdAt = json['created_at'];
    itemType = json['item_type'];
    subcategoryIds = json['subcategory_ids'].cast<String>();
    mainSubcategory = json['main_subcategory'];
    storeId = json['store_id'];
    visible = json['visible'];
    description = json['description'];
    images = json['images'].cast<String>();
    name = json['name'];
    if (json['custom_infos'] != null) {
      customInfos = <CustomInfos>[];
      json['custom_infos'].forEach((v) {
        customInfos!.add(CustomInfos.fromJson(v));
      });
    }
    if (json['prices'] != null) {
      prices = <Prices>[];
      json['prices'].forEach((v) {
        prices!.add(Prices.fromJson(v));
      });
    }
    emergencyStock = json['emergency_stock'];
    availableStock = json['available_stock'];
    minPriceValid = json['min_price_valid'];
    variationItems = json['variation_items'].cast<String>();
    relatedItems = json['related_items'].cast<String>();
    slug = json['slug'];
    brand = json['brand'];
    unitType = json['unit_type'];
    incrementValue = json['increment_value'];
    shipping = json['shipping'] != null
        ? Shipping.fromJson(json['shipping'])
        : null;
    keywords = json['keywords'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['item_type'] = itemType;
    data['subcategory_ids'] = subcategoryIds;
    data['main_subcategory'] = mainSubcategory;
    data['store_id'] = storeId;
    data['visible'] = visible;
    data['description'] = description;
    data['images'] = images;
    data['name'] = name;
    if (customInfos != null) {
      data['custom_infos'] = customInfos!.map((v) => v.toJson()).toList();
    }
    if (prices != null) {
      data['prices'] = prices!.map((v) => v.toJson()).toList();
    }
    data['emergency_stock'] = emergencyStock;
    data['available_stock'] = availableStock;
    data['min_price_valid'] = minPriceValid;
    data['variation_items'] = variationItems;
    data['related_items'] = relatedItems;
    data['slug'] = slug;
    data['brand'] = brand;
    data['unit_type'] = unitType;
    data['increment_value'] = incrementValue;
    if (shipping != null) {
      data['shipping'] = shipping!.toJson();
    }
    data['keywords'] = keywords;
    return data;
  }
}

class CustomInfos {
  String? field;
  String? value;

  CustomInfos({field, value});

  CustomInfos.fromJson(Map<String, dynamic> json) {
    field = json['field'];
    value = json['value'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['field'] = field;
    data['value'] = value;
    return data;
  }
}

class Prices {
  String? id;
  String? internalCode;
  String? title;
  int? qtdStock;
  double? price;
  double? promoPrice;
  String? promoEndAt;
  List<String>? barCodes;

  Prices(
      {id,
      internalCode,
      title,
      qtdStock,
      price,
      promoPrice,
      promoEndAt,
      barCodes});

  Prices.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    internalCode = json['internal_code'];
    title = json['title'];
    qtdStock = json['qtd_stock'];
    price = json['price'];
    promoPrice = json['promo_price'];
    promoEndAt = json['promo_end_at'];
    barCodes = json['bar_codes'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['internal_code'] = internalCode;
    data['title'] = title;
    data['qtd_stock'] = qtdStock;
    data['price'] = price;
    data['promo_price'] = promoPrice;
    data['promo_end_at'] = promoEndAt;
    data['bar_codes'] = barCodes;
    return data;
  }
}

class Shipping {
  bool? deliverable;

  Shipping({deliverable});

  Shipping.fromJson(Map<String, dynamic> json) {
    deliverable = json['deliverable'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['deliverable'] = deliverable;
    return data;
  }
}

class CollectionItems {
  String? id;
  String? title;
  String? slug;
  List<Items>? items;

  CollectionItems({id, title, slug, items});

  CollectionItems.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    slug = json['slug'];
    if (json['items'] != null) {
      items = <Items>[];
      json['items'].forEach((v) {
        items!.add(Items.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['slug'] = slug;
    if (items != null) {
      data['items'] = items!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Items {
  String? id;
  String? createdAt;
  String? itemType;
  List<String>? subcategoryIds;
  String? mainSubcategory;
  String? storeId;
  bool? visible;
  String? description;
  List<String>? images;
  String? name;
  List<CustomInfos>? customInfos;
  List<Prices>? prices;
  bool? availableStock;
  double? minPriceValid;
  List<String>? variationItems;
  List<String>? relatedItems;
  String? slug;
  String? brand;
  String? unitType;
  double? incrementValue;
  Shipping? shipping;
  int? emergencyStock;
  bool? showInMainPage;
  String? keywords;

  Items(
      {id,
      createdAt,
      itemType,
      subcategoryIds,
      mainSubcategory,
      storeId,
      visible,
      description,
      images,
      name,
      customInfos,
      prices,
      availableStock,
      minPriceValid,
      variationItems,
      relatedItems,
      slug,
      brand,
      unitType,
      incrementValue,
      shipping,
      emergencyStock,
      showInMainPage,
      keywords});

  Items.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    createdAt = json['created_at'];
    itemType = json['item_type'];
    subcategoryIds = json['subcategory_ids'].cast<String>();
    mainSubcategory = json['main_subcategory'];
    storeId = json['store_id'];
    visible = json['visible'];
    description = json['description'];
    images = json['images'].cast<String>();
    name = json['name'];
    if (json['custom_infos'] != null) {
      customInfos = <CustomInfos>[];
      json['custom_infos'].forEach((v) {
        customInfos!.add(CustomInfos.fromJson(v));
      });
    }
    if (json['prices'] != null) {
      prices = <Prices>[];
      json['prices'].forEach((v) {
        prices!.add(Prices.fromJson(v));
      });
    }
    availableStock = json['available_stock'];
    minPriceValid = json['min_price_valid'];
    variationItems = json['variation_items'].cast<String>();
    relatedItems = json['related_items'].cast<String>();
    slug = json['slug'];
    brand = json['brand'];
    unitType = json['unit_type'];
    incrementValue = json['increment_value'];
    shipping = json['shipping'] != null
        ? Shipping.fromJson(json['shipping'])
        : null;
    emergencyStock = json['emergency_stock'];
    showInMainPage = json['show_in_main_page'];
    keywords = json['keywords'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['item_type'] = itemType;
    data['subcategory_ids'] = subcategoryIds;
    data['main_subcategory'] = mainSubcategory;
    data['store_id'] = storeId;
    data['visible'] = visible;
    data['description'] = description;
    data['images'] = images;
    data['name'] = name;
    if (customInfos != null) {
      data['custom_infos'] = customInfos!.map((v) => v.toJson()).toList();
    }
    if (prices != null) {
      data['prices'] = prices!.map((v) => v.toJson()).toList();
    }
    data['available_stock'] = availableStock;
    data['min_price_valid'] = minPriceValid;
    data['variation_items'] = variationItems;
    data['related_items'] = relatedItems;
    data['slug'] = slug;
    data['brand'] = brand;
    data['unit_type'] = unitType;
    data['increment_value'] = incrementValue;
    if (shipping != null) {
      data['shipping'] = shipping!.toJson();
    }
    data['emergency_stock'] = emergencyStock;
    data['show_in_main_page'] = showInMainPage;
    data['keywords'] = keywords;
    return data;
  }
}

class Prices2 {
  String? id;
  String? internalCode;
  String? title;
  double? qtdStock;
  double? price;
  List<String>? barCodes;
  double? promoPrice;
  String? promoEndAt;
  int? maxQtdPerClient;

  Prices2(
      {id,
      internalCode,
      title,
      qtdStock,
      price,
      barCodes,
      promoPrice,
      promoEndAt,
      maxQtdPerClient});

  Prices2.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    internalCode = json['internal_code'];
    title = json['title'];
    qtdStock = json['qtd_stock'];
    price = json['price'];
    barCodes = json['bar_codes'].cast<String>();
    promoPrice = json['promo_price'];
    promoEndAt = json['promo_end_at'];
    maxQtdPerClient = json['max_qtd_per_client'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['internal_code'] = internalCode;
    data['title'] = title;
    data['qtd_stock'] = qtdStock;
    data['price'] = price;
    data['bar_codes'] = barCodes;
    data['promo_price'] = promoPrice;
    data['promo_end_at'] = promoEndAt;
    data['max_qtd_per_client'] = maxQtdPerClient;
    return data;
  }
}




